# DATABASE NAME
WHOOFI = 'Whoofi'
# COLLECTION NAME
DOG_OWNER = 'dog_owner'
DOG_WALKER = 'dog_walker'
DOG = 'dog'
# USER TYPE
WALKER = 'walker'
OWNER = 'owner'
# COLLECTIONS KEYS
ID = '_id'
USERNAME = 'username'
USER_TYPE = 'user_type'
EMAIL = 'email'
COORDINATES = 'coordinates'
PHONE_NUMBER = 'phone_number'
PASSWORD = 'password'
DOGS = 'dogs'
AGE = 'age'
YEARS_OF_EXPERIENCE = 'years_of_experience'
HOURLY_RATE = 'hourly_rate'
NAME = 'name'
RACE = 'race'
OWNER_ID = 'owner_id'
WEIGHT = 'weight'
SIZE = 'size'

# DOG SIZE
SMALL = 'small'
MEDIUM = 'medium'
BIG = 'big'
